name: Run Python linters

on: [push, pull_request]

jobs:
  python-files:
    runs-on: ubuntu-latest
    outputs:
      filelist: ${{ steps.python-files.outputs.filelist }}
    steps:
    - uses: actions/checkout@v3
    - id: python-files
      run: |
        echo "fileslist=$(find . -type f -exec awk ' /^#!.*python/{print FILENAME} {nextfile}' {} + | tr '\n' ' ')" >> $GITHUB_OUTPUT

  pylint:
    runs-on: ubuntu-latest
    needs: [python-files]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.6
      uses: actions/setup-python@v4
      with:
        python-version: 3.6

    - uses: actions/cache@v3
      with:
        path: ~/pip-cache
        key: pip-3.6-${{ github.sha }}
        # allow cache hits from previous runs of the current branch,
        # parent branch, then upstream branches, in that order
        restore-keys: |
          pip-3.6-
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip --cache-dir ~/pip-cache install pylint
    - name: Run Pylint
      env:
        PYTHON_FILES: ${{ needs.python-files.outputs.filelist }}
      run: | # Change PYTHONPATH for different repo
        export PYTHONPATH=$PYTHONPATH:$PWD/src/scripts
        pylint --errors-only $PYTHON_FILES
  
  flake8:
    runs-on: ubuntu-latest
    needs: [python-files]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.6
      uses: actions/setup-python@v4
      with:
        python-version: 3.6

    - uses: actions/cache@v3
      with:
        path: ~/pip-cache
        key: pip-3.6-${{ github.sha }}
        # allow cache hits from previous runs of the current branch,
        # parent branch, then upstream branches, in that order
        restore-keys: |
          pip-3.6-
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip --cache-dir ~/pip-cache install flake8
    - name: Run flake8
      env:
        PYTHON_FILES: ${{ needs.python-files.outputs.filelist }}
      run: | # Change PYTHONPATH for different repo
        export PYTHONPATH=$PYTHONPATH:$PWD/src/scripts
        flake8 --select F $PYTHON_FILES
